name = "lean-derived-categories"
version = "0.1.0"
defaultTargets = ["LeanDerivedCategories"]

[[lean_lib]]
name = "LeanDerivedCategories"

[[require]]
name = "mathlib"
git = "https://github.com/joelriou/mathlib4.git"
rev = "d886e33fd2f029f2304dfd20d9069d5fa7f3aa1a"

